version: '3'
services:
    core:
        image: hypersignprotocol/core
        hostname: hypersign-core
        environment:
            PORT: 5000 
            # LOG_FILEPATH: "/usr/app/log/core.log" 
            # LOG_DIR: "/usr/app/log/" 
            LOG_TIMESTAMP_FORMAT: "YYYY-MM-DD HH:mm:ss.SSS" 
            LOG_LEVEL: "debug" 
            DATABASE_FILEPATH: "/usr/src/app/dist/ssi.db" 
            JWT_SECRET: "mysecreEtKeY@123" 
        # volumes:
        #    - core_db:/home/aeternity/node/data/mnesia

    explorer:
        image: hypersignprotocol/explorer:env
        hostname: hypersign-explorer
        environment:
            PORT: 5001 
            VUE_APP_TITLE: "HyperSign Identity Explorer (dockerCompose)"
            VUE_APP_DESC: "DID Explorer for Hypersign Identity network!"
            VUE_APP_STUDIO_BASE_URL: "http://localhost:9001/"
            VUE_APP_NODE_SERVER_BASE_URL: "http://localhost:5000/"
            VUE_APP_NODE_SERVER_NETWORK_STATUS_EP: "network/info"
            VUE_APP_NODE_SERVER_SCHEMA_LIST_EP: "api/schema/list"
            VUE_APP_NODE_SERVER_SCHEMA_GET_EP: "api/schema/get/"
            VUE_APP_NODE_SERVER_DID_LIST_EP: "api/did/list"
            VUE_APP_NODE_SERVER_DID_CREATE_EP: "api/did/create"
            VUE_APP_NODE_SERVER_DID_RERSOLVE_EP: "api/did/resolve/" 
        depends_on:
            - core

    studio-server:
        image: hypersignprotocol/studio-server
        hostname: hypersign-studio-server
        environment:
            PORT: 9000
            # LOG_FILEPATH: "/usr/app/log/studio-server.log" 
            # LOG_DIR: "/usr/app/log/" 
            LOG_TIMESTAMP_FORMAT: "YYYY-MM-DD HH:mm:ss.SSS" 
            LOG_LEVEL: "debug" 
            DATABASE_FILEPATH: "/usr/src/app/dist/ssi.db" 
            JWT_SECRET: "mysecreEtKeY@123" 

    studio-client:
        image: hypersignprotocol/studio-client:env
        hostname: hypersign-studio-client
        environment:
            PORT: 9001
            VUE_APP_TITLE: "Hypersign Studio (dockerCompose)"
            VUE_APP_DESC: "A portal to issue and verify credentials on Hypersign Identity network!"
            VUE_APP_STUDIO_SERVER_BASE_URL: "http://localhost:9000/"
            VUE_APP_STUDIO_SERVER_CRED_LIST_EP: "api/credential/list"
            VUE_APP_STUDIO_SERVER_CRED_ISSUE_EP: "api/credential/issue"
            VUE_APP_STUDIO_SERVER_AUTH_CHALLENGE_EP: "api/auth/challenge"
            VUE_APP_STUDIO_SERVER_AUTH_LOGIN_EP: "api/auth/login"
            VUE_APP_NODE_SERVER_BASE_URL: "http://localhost:5000/"
            VUE_APP_NODE_SERVER_SCHEMA_LIST_EP: "api/schema/list"
            VUE_APP_NODE_SERVER_SCHEMA_GET_EP: "api/schema/get"
            VUE_APP_NODE_SERVER_SCHEMA_CREATE_EP: "api/schema/create"
            VUE_APP_EXPLORER_BASE_URL: "http://localhost:5001/"
            VUE_APP_EXPLORER_NEW_DID_EP: "explorer/newdid"
        depends_on:
            - core
            - explorer
            - studio-server
    
    proxy:
        image: nginx:1.13.8
        hostname: proxy
        ports:
        - "5000:5000"
        - "5001:5001"
        - "9001:9001"
        - "9000:9000"
        volumes:
        - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ${PWD}/nginx/cors.conf:/etc/nginx/cors.conf

# volumes:
#   core_db:
#   server_db:
