version: '3'
services:
    core:
        image: hypersignprotocol/core:v1.0
        hostname: core
        environment:
            - PORT=5000
            - LOG_LEVEL=debug
            - JWT_SECRET=mysecreEtKeY@123
            - RECAPTCHA_SECRET=<YOUR RECAPTCHA SECRET>
        ports: 
            - '5000:5000'
   
    studio-server:
        image: hypersignprotocol/studio-server:v1.0
        environment:
            - PORT=9000
            - HOST=localhost
            - LOG_LEVEL=debug
            - JWT_SECRET=mysecreEtKeY@123
            - NODE_SERVER_BASE_URL=http://core:5000/
            - NODE_SERVER_DID_CREATE_EP=api/did/create_tmp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_PORT=465 
            - MAIL_USERNAME=<YOUR EMAIL>
            - MAIL_PASSWORD=<YOUR PASSWORD>
            - MAIL_NAME=Hypersign Admin
        depends_on: [core]
        ports: 
            - '9000:9000'

    studio-client:
        image: hypersignprotocol/studio-client:v1.0
        environment: 
            - VUE_APP_TITLE=Studio
            - VUE_APP_VERSION=v1.0
            - VUE_APP_STUDIO_SERVER_BASE_URL=http://localhost:9000/
            - VUE_APP_NODE_SERVER_BASE_URL=http://localhost:5000/
            - VUE_APP_EXPLORER_BASE_URL=http://localhost:5001/
        ports: 
            - '9001:80' 
        
    explorer:
        image: hypersignprotocol/explorer:v1.0
        environment: 
            - VUE_APP_TITLE=Identity Explorer
            - VUE_APP_VERSION=v1.0
            - VUE_APP_STUDIO_BASE_URL=http://localhost:9001/
            - VUE_APP_NODE_SERVER_BASE_URL=http://localhost:5000/
            - VUE_APP_RECAPTCHA_SITE_KEY=<YOUR RECAPTCHA SITE KEY>
        ports: 
            - '5001:80'

    